name: Rust and Pyright CI

on:
  push:
    paths-ignore:
        - '.github/workflows/*.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/*yml'
  workflow_dispatch:

jobs:
  rust-pyright:
    name: Test rust and pyright
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyright
      - name: Run Ruff - Linting
        run: ruff check .
      - name: Run Ruff - Import Sorting
        run: ruff check . --select I001
      - name: Run Ruff - Autoformatting
        run: ruff check . --fix
    #   - name: Run Pytest
    #     run: pytest