name: Rust and Pyright CI

on:
  push:
    paths-ignore:
        - '.github/workflows/*.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/*yml'
  workflow_dispatch:

jobs:
  rust-pyright:
    name: Test rust and pyright
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pyright pytest
      - name: Run Black
        run: black .
      - name: Run Ruff - Autoformatting
        run: ruff check . --config ruff.yml --fix
      - name: Run Pytest
        run: pytest

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply formatting fixes"
          git push
        if: success()
