name: Find Python Version

on:
  push:
    paths-ignore:
      - '.github/workflows/*.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  find-version:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Print versions
        run: |
          python --version
          npm --version
      # - name: Checkout Code