name: Find Python Version

on:
  push:
    paths-ignore:
      - '.github/workflows/*.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  find-version:
    # name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # - pyright vs mypy, isort, flake8 or pylint. ruff with precommit
      # 1) Order of CI operations, test(pytest), autoformat (ruff), lint (flake8 or pylint or ruff)
      - name: Print versions
        run: |
          python --version
          npm --version
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install black isort pyright pylint pytest
      - name: Run Black
        run: black . --check
      - name: Run isort
        run: isort . --check
      - name: Run Pyright
        run: pyright .
      - name: Run Pylint
        # run: python -m pylint **/*.py
        run: pylint .
      - name: Run Pytest
        run: pytest
