name: Find Python Version

on:
  push:
    paths-ignore:
      - '.github/workflows/*.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  find-version:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Print versions
        run: |
          python --version
          npm --version
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python 3.10.15
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run Pulint
        run: python -m pylint **/*.py